[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

# Optional: Set environment variables if needed
#[[redirects]]
#from = "/api/*"
#to = "https://your-backend.example.com/:splat"
#status = 200
#force = true
